language: python
os: linux
dist: xenial
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: checkout
      install: 
        - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git checkout -qf $TRAVIS_COMMIT
      script: skip
    - stage: tests
      script: python3 -m pytest tests/test_dice.py
    - stage: deploy to staging
      script: skip
      deploy:
        provider: heroku
        strategy: api
        app: ahurtadoc-ci-learn-staging
        api_key: $HEROKU_TOKEN
        on:
          - branch: main
    - stage: test staging
      script: curl https://ahurtadoc-ci-learn-staging.herokuapp.com
    - stage: deploy to production
      script: skip
      deploy:
        provider: heroku
        strategy: api
        app: ahurtadoc-ci-learn-prod
        api_key: $HEROKU_TOKEN
        on:
          - branch: main
    - stage: test production
      script: curl https://ahurtadoc-ci-learn-prod.herokuapp.com