language: python
os: linux
dist: xenial
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: checkout
      install: 
        - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git checkout -qf $TRAVIS_COMMIT
      script: skip
    - stage: tests
      script: python3 -m pytest tests/test_dice.py
